import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { ReactNode } from "react";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: { children: ReactNode }) {
  return (
    <html lang="en">
      <body className="bg-black text-white">

        {/* NAVBAR */}
        <nav className="fixed top-0 w-full z-50 backdrop-blur-md bg-black/70 border-b border-gray-800">
          <div className="max-w-6xl mx-auto px-6 py-4 flex justify-between items-center">

            <a href="/" className="font-semibold text-lg">
              Zubin Mehta
            </a>

            <div className="flex gap-6 text-sm text-gray-300">
              <a href="/about" className="hover:text-white transition">About</a>
              <a href="/projects" className="hover:text-white transition">Projects</a>
              <a href="/contact" className="hover:text-white transition">Contact</a>
            </div>

          </div>
        </nav>

        {/* PAGE CONTENT */}
        <div className="pt-20">
          {children}
        </div>

      </body>
    </html>
  );
}